# Generated by Django 5.1.6 on 2025-03-06 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_chat', '0003_alter_chat_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-created_at',)},
        ),
    ]
