# Generated by Django 5.1.6 on 2025-03-06 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_chat', '0004_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
