# Generated by Django 5.1.6 on 2025-03-07 09:55

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_chat', '0006_userchatstatus_last_deleted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchatstatus',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 7, 9, 55, 22, 171378, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterUniqueTogether(
            name='userchatstatus',
            unique_together={('user', 'chat')},
        ),
    ]
