# Generated by Django 5.1.6 on 2025-03-07 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_chat', '0007_alter_userchatstatus_last_viewed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchatstatus',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 7, 9, 56, 17, 568522, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
