# Generated by Django 5.1.6 on 2025-03-07 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_chat', '0010_alter_userchatstatus_last_viewed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchatstatus',
            name='last_deleted_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 7, 10, 18, 7, 489503, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userchatstatus',
            name='last_viewed_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 7, 10, 18, 7, 489572, tzinfo=datetime.timezone.utc)),
        ),
    ]
