# Generated by Django 5.1.6 on 2025-03-08 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_chat', '0012_alter_userchatstatus_last_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchatstatus',
            name='last_deleted_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 8, 14, 47, 25, 996173, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userchatstatus',
            name='last_viewed_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 8, 14, 47, 25, 996217, tzinfo=datetime.timezone.utc)),
        ),
    ]
