# Generated by Django 5.1.7 on 2025-03-10 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_chat', '0017_alter_userchatstatus_last_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchatstatus',
            name='last_deleted_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 10, 16, 6, 22, 255590, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userchatstatus',
            name='last_viewed_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 10, 16, 6, 22, 255623, tzinfo=datetime.timezone.utc)),
        ),
    ]
