# Generated by Django 5.1.7 on 2025-03-10 16:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_chat', '0019_alter_userchatstatus_last_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchatstatus',
            name='last_deleted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userchatstatus',
            name='last_viewed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
